### PR TITLE
Update helpers.js

### LINKED ISSUE #48: Cannot get model of name accessToken from app.models
loopback 2.14.0
loopback-testing 1.1.0

my test file:

        var lt = require('loopback-testing');
        var should = require('should');
        var app = require('../server/server.js');
        
        describe('/jobs', function () {
          lt.beforeEach.withApp(app);
          lt.it.shouldBeAllowedWhenCalledAnonymously('GET', '/api/jobs/list');
        });

Getting error "AssertionError: cannot get model of name accessToken from app.models", looks like the internally defined model is named "AccessToken" (capitalized) instead of "accessToken".

### PR DESCRIPTION
**Pull request by vladmiller**
Default model is called AccessToken (with capital A)

Fix #48

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by vladmiller** [comment]
@slnode Should I add this comment?

**Comment by bajtos** [comment]
@vladmiller  thank you for the pull request. We need you to sign our CLA before it can be merged - see https://cla.strongloop.com/agreements/strongloop/loopback-testing

The change LGTM, but we need to check that this patch is not breaking loopback unit-tests before merging.

**Comment by bajtos** [comment]
@vladmiller ping, could you please sign our CLA?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by vladmiller** [comment]
@bajtos Sorry, missed your request. CLA signed

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Landed, thank you for the contribution.

**Pull request merged**
