### PR TITLE
Proof of duplicate data and reason for cleanDatasources

### PR DESCRIPTION
**Pull request by jrschumacher**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
As I commented [elsewhere](https://github.com/strongloop/loopback-example-full-stack/pull/53#issuecomment-70674372), this would be fixed by adding `beforeEach.givenModel`.

I think it makes sense to add the tests from this patch though, can you include them in #40 please?

**Comment by bajtos** [comment]
@ritch I am assigning the PR to you since you are reviewing #40 too.

**Comment by jrschumacher** [comment]
> I think it makes sense to add the tests from this patch though, can you include them in #40 please?
Yes

**Comment by jrschumacher** [comment]
@ritch closing as this PR is only an proof to the issue

**Pull request closed without merging**
