### PR TITLE
Fixed: no login method

### PR DESCRIPTION
**Pull request by guanbo**
My user model is 'account'

account.json

```json
  "name": "account",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
...
```

account-test.js
```js
var lt = require('loopback-testing');
var assert = require('assert');
var app = require('../server/server.js'); 
var querystring = require('querystring')

var loggedInUser = {email:"gbo2@example.com", password: "123456", id: 123456, companyId:4}

describe('# Account', function() {
  lt.beforeEach.withApp(app);
  lt.beforeEach.withUserModel('account');
  lt.beforeEach.givenLoggedInUser(loggedInUser);

...
```

with `constructor`, raise error: `no login method`, so remove it.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by myles-harding-livebookings** [comment]
I just had the same issue as the op. made the change shown in the commit and it fixed it for me. My scenario also has a custom model with the base as User.

Changed _beforeEach.givenLoggedInUser and _beforeEach.givenLoggedInUserWithRole where they both use "constructor".

**Comment by LoicMahieu** [comment]
ping @ritch @bajtos 
This PR is really old and it made this package completely not usable with recent loopback applications.

**Comment by LoicMahieu** [comment]
Duplicate #63

**Comment by bajtos** [comment]
Closed via #63

**Pull request closed without merging**
