### PR TITLE
Update helpers.js

### PR DESCRIPTION
**Pull request by vladmiller**
You might need to pass more parameters in role if you extend built-in role model

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by vladmiller** [comment]
Meaning of this patch is following: instead of role name you can pass object with role definition

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@vladmiller thank you for the pull request. We need you to sign our CLA before it can be merged - see https://cla.strongloop.com/agreements/strongloop/loopback-testing

**Comment by vladmiller** [comment]
@bajtos CLA signed

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
LGTM. @ritch do you have any objections against landing this change?

**Comment by vladmiller** [comment]
@bajtos the reason why I did it because I had extended Role with additional parameters

**Comment by ritch** [comment]
Nope LGTM

**Pull request merged**
