### PR TITLE
Add withUserModel to extend user related helpers

### PR DESCRIPTION
**Pull request by jrschumacher**

### CODE REVIEW

**Comment by jrschumacher** [comment]
@bajtos could I have your help with this? I am trying to extend the user helpers to allow the user to specify the model, but I am having issues using the constructor.

**Comment by bajtos** [comment]
Sorry @jrschumacher, I really don't want to invest my time into these helpers.

@ritch What's your position, are you keen to keep maintaining these helpers? Shall we move them to a new module maintained by the community?

**Comment by jrschumacher** [comment]
@bajtos I understand. I'm fine with moving away from this as well. 

I'd suggest making a note in the readme about the status of the helpers.

**Comment by jrschumacher** [comment]
@bajtos maybe it would be a good idea to make this into a list of testing recipes. So just a collection of md files and some examples. Which should be easier to maintain.

**Comment by ritch** [comment]
@jrschumacher https://github.com/strongloop/loopback-testing/issues/53

**Comment by jrschumacher** [comment]
@ritch The linked issue is a question for me or just a notice?

**Comment by ritch** [comment]
Just a heads up... I'm guessing you have some useful feedback though.

We can merge this... its entirely additive.

**Pull request merged**
